amcl:
  ros__parameters:
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    # This creates a "safety zone" around your robot
    footprint: "[ [0.3, 0.2], [0.3, -0.2], [-0.3, -0.2], [-0.3, 0.2] ]"
