# nav2_params.yaml


amcl:
  ros__parameters:
    use_sim_time: true
    scan_topic: /scan
    odom_topic: /odom
    base_frame_id: base_link
    odom_frame_id: odom
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.2
    update_min_a: 0.2
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: 'home/semegn/my_farm_map.yaml'

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 2.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.25

controller_server:
  ros__parameters:
    use_sim_time: true
    expected_controller_frequency: 20.0
    odom_topic: /odom
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      lookahead_time: 1.0
      min_lookahead_distance: 0.2
      
velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 20.0
    cmd_vel_in_topic: /cmd_vel_nav
    cmd_vel_out_topic: /cmd_vel


bt_navigator:
  ros__parameters:
    use_sim_time: true
    bt_xml_filename: "navigate_w_replanning_time.xml"

recoveries_server:
  ros__parameters:
    use_sim_time: true
    expected_recoveries_frequency: 2.0

transformations:
  ros__parameters:
    use_sim_time: true

global_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_footprint
    update_frequency: 5.0
    publish_frequency: 1.0
    always_send_full_costmap: true
    track_unknown_space: false 
    rolling_window: false
    robot_radius: 0.25
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: "scan"
      scan:
        topic: /scan
        data_type: LaserScan
        marking: true
        clearing: true
        expected_update_rate: 20.0
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.25

local_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: odom
    robot_base_frame: base_footprint
    update_frequency: 5.0
    publish_frequency: 1.0
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.05
    robot_radius: 0.25
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: "scan"
      scan:
        topic: /scan
        data_type: LaserScan
        marking: true
        clearing: true
        expected_update_rate: 20.0
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.25

